# dist: trusty
# sudo: required
# language: node_js




os:
  - linux
  - osx

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: node_js
      node_js: "9"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      dist: trusty
      sudo: required
      language: node_js
      services: docker
# language: generic


cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

services:
  - docker

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CHROME_BIN=chromium-browser
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      # uncomment once integration tests are included in CI
      # docker pull dternyak/eth-priv-to-addr:latest
      sudo apt-get install libusb-1.0     
    fi
  # - |
  #   if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then

  #   fi

  
install:
  - npm install --silent

jobs:
  include:
    - stage: test
      script: npm run prettier:diff
      if: env(TRAVIS_OS_NAME)=linux
    - stage: test
      script: npm run test:coverage -- --maxWorkers=2 && npm run report-coverage
      if: env(TRAVIS_OS_NAME)=linux
    - stage: test
      script: npm run tslint && npm run tscheck && npm run freezer && npm run freezer:validate
      if: env(TRAVIS_OS_NAME)=linux
    - stage: electron
      script: npm run build:electron
      if: env(TRAVIS_OS_NAME)=osx
notifications:
  email:
    on_success: never
    on_failure: never

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"