FROM electronuserland/builder:wine

RUN mkdir /hostHome

RUN apt-get update && apt-get install -y libusb-1.0 nasm graphicsmagick autoconf automake libtool python-pip

# RUN pip install awscli --upgrade --user


# VOLUME ["/appDir"]

# WORKDIR /appDir

# ENTRYPOINT [ "/bin/bash", "-c" ]
