FROM electronuserland/builder:wine

RUN apt-get update && apt-get install -y libusb-1.0 nasm graphicsmagick autoconf automake libtool

# VOLUME ["/appDir"]

# WORKDIR /appDir

# ENTRYPOINT [ "/bin/bash", "-c" ]
