pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'jenkins/Docker'
            args '-v /home:/hostHome --env ETH_SIGNING_KEY=$ETH_SIGNING_KEY'
        }
    }
    stages {
        stage('Build') { 
            environment {
                ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES = 1
            }
            steps {
                sh 'rm -rf node_modules'
                sh 'npm install'
                sh 'npm run jenkins:electron:linux'
            }
        }
    }
}