pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'jenkins/Docker'
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'rm -rf node_modules'
                sh 'npm install' 
                sh 'npm run build:electron:linux'
            }
        }
    }
}