pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'jenkins/Docker'
        }
    }
    stages {
        stage('Build') { 
            environment {
                ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES = 1
            }
            steps {
                sh 'rm -rf node_modules'
                sh 'npm install' 
                sh 'npm run build:electron:linux'
                sh 'pwd'
                sh 'cp -r ./dist/electron-builds ~/jenkinsOut/linux'
                sh 'npm run build:electron:windows'
                sh 'cp -r ./dist/electron-builds ~/jenkinsOut/windows'
            }
        }
    }
}